repos:
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v3.2.0
    hooks:
      - id: conventional-pre-commit
        stages: [ commit-msg ]
        args: [ ]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.4.2
    hooks:
      # Run the linter.
      - id: ruff
        types_or: [ python ]
        args: [ "--fix", "--show-fixes" ]
      # Run the formatter.
      - id: ruff-format
        types_or: [ python ]