# Generated by Django 5.0.3 on 2024-04-08 00:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_number', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='BusStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Plane',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plane_number', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='BusTravel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_time', models.DateTimeField()),
                ('arrival_time', models.DateTimeField()),
                ('bus_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket_selling_app.bus')),
                ('bus_station_arrival_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bus_station_arrival', to='ticket_selling_app.busstation')),
                ('bus_station_departure_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bus_station_departure', to='ticket_selling_app.busstation')),
            ],
        ),
        migrations.CreateModel(
            name='BusTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('bus_travel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket_selling_app.bustravel')),
            ],
        ),
        migrations.AddField(
            model_name='busstation',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket_selling_app.city'),
        ),
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket_selling_app.city')),
            ],
        ),
        migrations.CreateModel(
            name='PlaneTravel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_time', models.DateTimeField()),
                ('arrival_time', models.DateTimeField()),
                ('airport_arrival_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='airport_arrival', to='ticket_selling_app.airport')),
                ('airport_departure_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='airport_departure', to='ticket_selling_app.airport')),
                ('plane_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket_selling_app.plane')),
            ],
        ),
        migrations.CreateModel(
            name='PlaneTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('plane_travel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket_selling_app.planetravel')),
            ],
        ),
    ]
